export const SKILL_LABELS = {
  acr: "Acrobatics",
  alc: "Alchemy",
  ani: "Animal Handling",
  ath: "Athletics",
  com: "Command",
  cou: "Counsel",
  cra: "Craft",
  dis: "Discipline",
  hea: "Healing",
  ins: "Insight",
  lin: "Linguistics",
  lor: "Lore",
  mel: "Melee",
  obs: "Observation",
  par: "Parry",
  per: "Persuade",
  ran: "Ranged Weapons",
  res: "Resistance",
  sai: "Sailing",
  soc: "Society",
  sor: "Sorcery",
  ste: "Stealth",
  sur: "Survival",
  thi: "Thievery",
  war: "Warfare"
};